basePath: /api/v1
definitions:
  api.CreateOwnerRequest:
    properties:
      email_address:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
      picture_data:
        type: string
      zip_code:
        type: integer
    required:
    - email_address
    - first_name
    - last_name
    - password
    - zip_code
    type: object
  api.CreatePetRequest:
    properties:
      birth_date:
        type: string
      name:
        type: string
      owner_id:
        type: integer
      picture_URL:
        type: string
    required:
    - birth_date
    - name
    - owner_id
    type: object
  api.CreatePostRequest:
    properties:
      body:
        type: string
      owner_id:
        type: integer
      post_type:
        type: integer
      title:
        type: string
    required:
    - body
    - owner_id
    - post_type
    - title
    type: object
  api.UpdateOwnerRequest:
    properties:
      email_address:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      owner_ID:
        type: integer
      password:
        type: string
      picture_data:
        type: string
      zip_code:
        type: integer
    required:
    - email_address
    - first_name
    - last_name
    - owner_ID
    - password
    - zip_code
    type: object
  api.UpdatePetRequest:
    properties:
      birth_date:
        type: string
      name:
        type: string
      owner_id:
        type: integer
      pet_ID:
        type: integer
      picture_URL:
        type: string
    required:
    - birth_date
    - name
    - owner_id
    - pet_ID
    type: object
  api.UpdatePostRequest:
    properties:
      body:
        type: string
      post_ID:
        type: integer
      title:
        type: string
    required:
    - body
    - post_ID
    - title
    type: object
host: localhost:8080
info:
  contact:
    email: support@socialwags.com
    name: API Support
    url: http://www.socialwags.com/support
  description: API documentation for the socialwags platform
  license: {}
  termsOfService: http://socialwags.com/terms/
  title: SocialWags API
  version: "1.0"
paths:
  /owner:
    delete:
      consumes:
      - application/json
      description: Delete a specific owner
      parameters:
      - description: Owner ID
        in: query
        name: owner_id
        type: integer
      produces:
      - application/json
      responses:
        "200": {}
      summary: Delete a specific owner
      tags:
      - Owner
    get:
      consumes:
      - application/json
      description: Get a specific owner
      parameters:
      - description: Owner ID
        in: query
        name: owner_id
        type: integer
      produces:
      - application/json
      responses:
        "200": {}
      summary: Get a specific owner
      tags:
      - Owner
    patch:
      consumes:
      - application/json
      description: Update a specific owner
      parameters:
      - description: Update user body
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/api.UpdateOwnerRequest'
      produces:
      - application/json
      responses:
        "200": {}
      summary: Update a specific owner
      tags:
      - Owner
    put:
      consumes:
      - application/json
      description: Create a new owner
      parameters:
      - description: Create owner request body
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/api.CreateOwnerRequest'
      produces:
      - application/json
      responses:
        "200": {}
      summary: Create a new owner account
      tags:
      - Owner
  /pet:
    delete:
      consumes:
      - application/json
      description: Delete a specific pet
      parameters:
      - description: Pet ID
        in: query
        name: pet_id
        type: integer
      produces:
      - application/json
      responses:
        "200": {}
      summary: Delete a specific pet
      tags:
      - Pet
    get:
      consumes:
      - application/json
      description: Get a specific pet
      parameters:
      - description: Pet ID
        in: query
        name: pet_id
        type: integer
      produces:
      - application/json
      responses:
        "200": {}
      summary: Get a specific pet
      tags:
      - Pet
    patch:
      consumes:
      - application/json
      description: Update pet
      parameters:
      - description: update pet request body
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/api.UpdatePetRequest'
      produces:
      - application/json
      responses:
        "200": {}
      summary: Update pet
      tags:
      - Pet
    put:
      consumes:
      - application/json
      description: Create a new pet
      parameters:
      - description: Create pet request body
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/api.CreatePetRequest'
      produces:
      - application/json
      responses:
        "200": {}
      summary: Create a new pet
      tags:
      - Pet
  /post:
    delete:
      consumes:
      - application/json
      description: Delete a specific post
      parameters:
      - description: Post ID
        in: query
        name: post_id
        type: integer
      produces:
      - application/json
      responses:
        "200": {}
      summary: Delete a specific post
      tags:
      - Post
    get:
      consumes:
      - application/json
      description: Get a specific post
      parameters:
      - description: Post ID
        in: query
        name: post_id
        type: integer
      produces:
      - application/json
      responses:
        "200": {}
      summary: Get a specific post
      tags:
      - Post
    patch:
      consumes:
      - application/json
      description: Update a specific post
      parameters:
      - description: Update post body
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/api.UpdatePostRequest'
      produces:
      - application/json
      responses:
        "200": {}
      summary: Update a specific post
      tags:
      - Post
    put:
      consumes:
      - application/json
      description: Create a new post
      parameters:
      - description: Create post request body
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/api.CreatePostRequest'
      produces:
      - application/json
      responses:
        "200": {}
      summary: Create a new post
      tags:
      - Post
swagger: "2.0"
